#
spring:
  application:
    name: hr
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.metrics.SystemMetricsAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.web.tomcat.TomcatMetricsAutoConfiguration
p6spy:
  config:
    registermbeans: false


#  profiles:
#    active: local